# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 299355989fed120e25d0fd878e1a2605a5d74b84d0731f2b2a87d2e065cb656be46dd4ef6dedd44708328eae4575c2f453572486f07f5d97ec8577c142ebb3d3

test:
  secret_key_base: 26a3f66ac8c58c2145612017e71283bbff4dcea314722af6bd5294dc5bc07a412a433c36ca2aa28827a4dd8e5df48bacb4b0dd8766e31664e2d53440773f44a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
